# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-extension-app"
client_id = "3cc1b4d56a0b223b847bf5e20a28bbb6"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
